version: '3.9'

services:
  db:
    image: postgres:15.3-alpine3.18
    restart: always
    ports:
      - '54321:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: test
      POSTGRES_DB: l0
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - /l0/lib/postgre:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: ./docker/migrator/Dockerfile
    depends_on:
      db:
        condition: service_healthy

  nats:
    image: nats-streaming:0.24-alpine3.15
    restart: always
    ports:
      - '127.0.0.1:4222:4222'


  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - migrator
      - nats
    ports:
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:9090:9090'